services:
  - type: web
    name: of-unread
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: ONLYFANS_ACCOUNT_ID
        sync: false
      - key: ONLYFANS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CF_IMAGES_ACCOUNT_HASH
        sync: false
      - key: CF_IMAGES_ACCOUNT_ID
        sync: false
      - key: CF_IMAGES_TOKEN
        sync: false
      - key: Cloudflare_Global_API_Key
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_OLD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: GITHUB_API_KEY
        sync: false
      - key: LIST_ID
        sync: false
